### PR TITLE
Fix minor typos in names

### PR DESCRIPTION
**Pull request by billdenney**
Minor typo fixes.  😉 

Thank you for the acknowledgement!

### CODE REVIEW

**Comment by mattfidler** [comment]
Thanks;  Sorry for the Name;  People misspell my name all the time too.

**Comment by billdenney** [comment]
No worries at all.

**Comment by mattfidler** [comment]
Maybe you can look at the documentation in nlmixrBoundsParser;  For some reason I cannot install with the roxygen generated `Rd` file.  I deleted it for now

**Comment by billdenney** [comment]
I'll check it out.  I just fixed another important issue for a likely common case.

**Pull request merged**
