### PR TITLE
Slight code simplification

### PR DESCRIPTION
**Pull request by billdenney**
I was looking through the code for something else, and I thought that this looked a bit easier to read as I was looking for the other thing.  If not of interest, no worries closing it without committing it.

### CODE REVIEW

**Comment by mattfidler** [comment]
This funny code was to support an older version of `vpc`.  If you add the `vpc` version requirement in the description file, I will merge the request.

**Comment by billdenney** [comment]
Let me check your preference here:  Would you prefer the update be to require `vpc::vpc_vpc` with a current-ish version of the `vpc` library in the DESCRIPTION?  (Where "current-ish" is defined as the oldest version of `vpc` where `vpc::vpc_vpc` exists?)  Or is it something else?

**Comment by mattfidler** [comment]
The update would require vpc::vpc_vpc to be current and the version of vpc to at least have that.  I think the current version of  `vpc` should sufficie.

**Comment by billdenney** [comment]
A quick look found that the first version with `vpc_vpc()` is 1.1.0 (https://www.rdocumentation.org/packages/vpc/versions/1.1.0/topics/vpc).  I'll add that as the required version and simplify the code.

**Comment by mattfidler** [comment]
Added this into nlmixr

**Pull request merged**
