### PR TITLE
Omega cov

### LINKED ISSUE #338: Add `cor()` option for omega initial conditions
And if you want to give a new feature to bounds, you could consider:
 
```r
a + b ~ cor(...)
```

To specify the correlation matrix/Sd values and then translate them to the covariance matrix

_Originally posted by @mattfidler in https://github.com/nlmixrdevelopment/nlmixr/issues/322#issuecomment-649461526_

### PR DESCRIPTION
**Pull request by billdenney**
Fix #338

### CODE REVIEW

**Comment by mattfidler** [comment]
Could you put your name as an author 

```r
#' @author Bill Denney, Matthew Fidler
```

Otherwise looks good to me.  I will have to test it too.

**Comment by billdenney** [comment]
There are no user-facing function changes here.  Where are you thinking of adding `@author`?  `ini()`?

**Comment by mattfidler** [comment]
Just in the noRd documentation

**Comment by mattfidler** [comment]
Also the ini function

**Pull request merged**
