### PR TITLE
Simplify model tests

### PR DESCRIPTION
**Pull request by mattfidler**
@billdenney Issue #99.  I merged your branch into a seperate branch here.

### CODE REVIEW

**Comment by mattfidler** [comment]
Perhaps there are too many tests.

NMQual used only a few tests:

https://bitbucket.org/metrumrg/nmqual/src/0bd9a0b0b5d4df300170505524c5d8ec9ae6ecdf/test/?at=master

**Comment by billdenney** [comment]
I'm not sure about the number of tests, but my preference is that every feature is tested.

With minimization and potential differences between platforms, I like having lots of tests.  Because while we could test for features, testing for numeric stability is hard without diving deep into every CPU/OS/math library/compiler combination (and testing all combinations there is effectively impossible).

**Comment by mattfidler** [comment]
Thanks Bill.  

I was just thinking when reviewing the Travis CI build file, I think that we could make travis run the nlmixr models one by one by judicious use of environmental variables.  I think it wont work on the Mac version, but it might with the Linux/ubuntu version.  I forgot I had travis install sympy.

**Comment by mattfidler** [comment]
I know the test suite is incomplete, since nlmixr does more than what is tested.  However, tests and documenation are lagging behind.

All the error structures in nlmixr's fo/foce/focei are tested in Wang2007 test, but the additive, additive+proportional error structures of nlme and saem are not tested right now.  

The theo example can be added to test the additive in every model;  I need to find an example of additive+proportional or simulate one.

I could also reparamterize to test the non-mu referencing of a few models since UI nlme handles these models differently.

**Comment by mattfidler** [comment]
Also multiple endpoint support isn't tested in the test suite.

**Comment by vjd** [comment]
@mattfidler how about we have a common set of datasets/models/results in a separate repository covering all features that any estimation software can use for testing? 

That way, the travis CI testing on the nlmixr itself is not slowed down by the multitude of tests. Also, we can have folks submit requests to that satellite repo. 

@billdenney what do you think? Perhaps you can also add PKNCA testing to that repo as long as there are NCA datasets and results there.

**Comment by vjd** [comment]
@kestrel99 - its not for one person to curate. But I'm willing to give it a hard start. But it will be good to have community discussion on setup and testing requirements.

**Comment by kestrel99** [comment]
@vjd Quite true, but as you say, needs someone to get the ball rolling. I suspect this team may be stretched a little thin to do it effectively

**Comment by mattfidler** [comment]
I agree with you about the value of having datasets to allow comparison.

However, having travis run the models allows to see if some things that are added break nlmixr.

**Comment by mattfidler** [comment]
Based on mac results (See Issue #120) I will be changing the default FOCEi minimization algorithm.

**Pull request merged**
