### PR TITLE
Dynmodel doc fix

### PR DESCRIPTION
**Pull request by billdenney**
The dynmodel examples wouldn't run as-is, so I fixed them.  (Related to nlmixrdevelopment/RxODE#215)

### CODE REVIEW

**Comment by mattfidler** [comment]
Thanks @billdenney 

Can you change to `camelCase`?  `nlmixr` and `RxODE` uses `camelCase` instead of `snake_case`;  consistency is important.  I have spent some time trying to clean up some of the inconsistencies.

**Comment by mattfidler** [comment]
This also leads me to believe that mason didn't upload all his changes since I had him fix this.

**Comment by billdenney** [comment]
@mattfidler, I'll try to remember to use camelCase for future modifications.  (I almost always use snake_case in my code, so I can almost guarantee that I'll slip up, but I won't take repeated reminders personally if you don't take the slip-ups personally.  ;) )  I agree that consistency is important.

**Comment by mattfidler** [comment]
I know;  We are in the minority.  I don't think we would every go to R open sci for that reason.

**Comment by mattfidler** [comment]
Since `RxODE` is camel case in its name I kept camelCase for nlmixr.  I also used the funny `ESS` underscore for many years so I still have some aversion to `snake_case`, though I am sure I need to get over it.

**Comment by billdenney** [comment]
Ahh, `ESS` I preferred that for a long time resisting the switch to RStudio.  (I now like RStudio better, but in its early days I definitely found `ESS` superior.)

**Comment by mattfidler** [comment]
I think it is a mixed bag;  For me, I wish `ESS` had some rstudio features (or `Rstudio` had some `ESS` features).  I likely won't switch to Rstudio until they have an ability to attach to a `gdb` or `valgrind` enabled R session like `ESS` can. This is very important to debugging some of the `C`/`C++` code for me. 

I have enabled the `RStudio` style in `ESS` so that indentation would be consistent between Rstudio and ESS.

**Comment by mattfidler** [comment]
Any of the indentation that is `4` spaces can be changed to `2`;  It is on my todo list (but not high).

**Comment by billdenney** [comment]
`styler:::style_active_pkg()` will do that (and a whole lot more) to standardize the code formatting.  It's an open question if the "whole lot more" part is what you want.

**Comment by mattfidler** [comment]
Not sure; I don't mind using it since it doesn't modify variable names;  I think I tried in the past and it broke something, but we will see this time.

**Comment by mattfidler** [comment]
748a6b58 is the styler commit.

**Comment by billdenney** [comment]
I don't see the styler commit right now.  Did you push it to foceiDur?

**Comment by mattfidler** [comment]
No.  Just `RxODE`;  

https://github.com/nlmixrdevelopment/RxODE/commit/748a6b58a365fef04f455c33988c367173a25b7c

I believe styler will may break nlmixr currently.  

Currently it changed:

```R
...
RxODE({
...
})
...
```

to 

```R
...
RxODE(
  {
...
  }
...
)

```

While it is mostly parsing

```R
ini({
})
model({
})
```

may not parse correctly.  I need to check this before I push any styler changes to `nlmixr`

**Pull request merged**
