### PR TITLE
Fix dynmodel inits bounds

### LINKED ISSUE #305: Inaccurate bound checking for dynmodel
I tried to run a dynmodel with bounds on the parameters, and I got what appears to be an inaccurate statement that my starting values violate bounds:

This is with the approximately-current foceiDur branch.

``` r
library(nlmixr)
model_onecmt_iv <- function(){
  ini({
    CL <- c(0,0.001,10) # Clearance (L/hr)
    V <- c(0,0.01,100) # Volume of Distribution
    prop.err <- c(0,0.1,1)
  })
  model({
    kel = CL/V
    d/dt(AC) = -kel*AC
    cp = AC/V
    cp ~ prop(prop.err)
  })
}

fit <- nlmixr(object=model_onecmt_iv, data=Bolus_1CPT, est="dynmodel")
#> creating full model...pruning branches (if/else)...done
#> loading into symengine environment...done
#> finding duplicate expressions in EBE model...
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00
#> optimizing duplicate expressions in EBE model...
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00
#> compiling EBE model...done
#> creating full model...pruning branches (if/else)...done
#> loading into symengine environment...done
#> finding duplicate expressions in EBE model...
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00
#> optimizing duplicate expressions in EBE model...
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00
#> compiling EBE model...done
#> creating full model...pruning branches (if/else)...done
#> loading into symengine environment...done
#> finding duplicate expressions in EBE model...
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00
#> optimizing duplicate expressions in EBE model...
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00
#> compiling EBE model...done
#> |-----+---------------+-----------+-----------+-----------|
#> |    #| Objective Fun |        CL |         V |      prop |
#> |    1|     433100.95 |    -1.000 |   -0.8182 |     1.000 |
#> |    U|     433100.95 |  0.001000 |   0.01000 |    0.1000 |
#> Error in minqa::bobyqa(par, fn, control = .ctl, lower = lower, upper = upper): Starting values violate bounds
```

<sup>Created on 2020-06-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

### PR DESCRIPTION
**Pull request by billdenney**
The initial conditions were not being exponentiated while the bounds were being exponentiated when setting up the dynmodel.  This exponentiates none of the values.  I'm not sure if that is the correct solution, but it seems like the same operation should be done for both inits and bounds.  And, I would assume that the user likely knows the right transformation-- if the estimate should be on the log scale, then they will take care of that.

Fixes #305 and should be applied after #304 to simplify review.

### CODE REVIEW

**Comment by billdenney** [comment]
P.S. To clarify:  Maybe the .inits should be exponentiated, too.  But, the same operation should occur for both.

**Comment by mattfidler** [comment]
In theory, nothing should be exponentiated , it should be handled by the model and initial conditions.  

Can you show me what you mean here?

**Comment by mattfidler** [comment]
In theory you would specify

```r
..
ini({
ta <- log(10)
})
model({
a <- exp(ta)
})
...
```
```

**Comment by billdenney** [comment]
Yeah, the thing that I am changing is, in effect, removing the `exp()` from lines 548 and 551 here:

https://github.com/nlmixrdevelopment/nlmixr/blob/e1a9cd1c168e1c4c46a8a4dec1516136a45b031b/R/utils.R#L547-L552

I agree that I would specify the model like that.  What I was trying to fix was to make the transform for `.inits`, `.lower`, and `.upper` the same.  Otherwise, I am getting the error indicating that the initial estimate is not between the bounds as described in #305.

**Comment by mattfidler** [comment]
Ok.  I reviewed and you are right.  Thanks for the catch (I haven't reviewed this yet).

**Comment by mattfidler** [comment]
It was difficult for me to see what you were talking about.  Thank you for taking the time to clarify.

**Pull request merged**
